# Generated by Django 6.1.1 on 2026-09-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=300)),
                ("answer", models.TextField()),
                ("category", models.CharField(default="General", max_length=80)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["order", "question"],
            },
        ),
        migrations.CreateModel(
            name="GalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("caption", models.CharField(max_length=200)),
                ("quote", models.CharField(blank=True, max_length=280)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="gallery/"),
                ),
                ("image_alt", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Gallery item",
                "verbose_name_plural": "Gallery items",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="SiteStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("learners_supported", models.PositiveIntegerField(default=0)),
                ("partner_schools", models.PositiveIntegerField(default=0)),
                ("educators_trained", models.PositiveIntegerField(default=0)),
                (
                    "families_recommend",
                    models.PositiveIntegerField(
                        default=0, help_text="Percentage of families who recommend us"
                    ),
                ),
                (
                    "learners_qualifier",
                    models.CharField(default="since 2015", max_length=80),
                ),
                (
                    "schools_qualifier",
                    models.CharField(default="across regions", max_length=80),
                ),
                (
                    "educators_qualifier",
                    models.CharField(default="workshops & coaching", max_length=80),
                ),
                (
                    "recommend_qualifier",
                    models.CharField(default="of surveyed families", max_length=80),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site statistics",
                "verbose_name_plural": "Site statistics",
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parent_name", models.CharField(max_length=120)),
                ("quote", models.TextField()),
                ("program", models.CharField(blank=True, max_length=160)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="testimonials/"),
                ),
                (
                    "role_label",
                    models.CharField(
                        default="Parent",
                        help_text="e.g. Parent, Educator",
                        max_length=80,
                    ),
                ),
                ("is_featured", models.BooleanField(default=True)),
                (
                    "consent_given",
                    models.BooleanField(
                        default=True, help_text="Photo/quote used with consent"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
