# Generated by Django 6.1.1 on 2026-09-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeaturePillar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("summary", models.CharField(max_length=280)),
                ("body", models.TextField()),
                ("icon", models.CharField(default="leaf", max_length=40)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Feature pillar",
                "verbose_name_plural": "Feature pillars",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField()),
                ("short_description", models.CharField(blank=True, max_length=300)),
                (
                    "age_group",
                    models.CharField(help_text="e.g. Ages 3–8", max_length=100),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("early_intervention", "Early Intervention"),
                            ("inclusive_learning", "Inclusive Learning"),
                            ("therapy_support", "Therapy & Family Support"),
                            ("academic_pathways", "Academic Pathways"),
                            ("educator_training", "Educator Training"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=40,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="CSS icon key, e.g. butterfly, heart, book",
                        max_length=40,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="programs/"),
                ),
                (
                    "highlights",
                    models.TextField(blank=True, help_text="One highlight per line"),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
    ]
