# Generated by Django 6.1.1 on 2026-09-09 06:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdmissionEnquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("child_name", models.CharField(max_length=120)),
                (
                    "age",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(25),
                        ]
                    ),
                ),
                (
                    "needs",
                    models.TextField(
                        help_text="Describe learning needs, strengths, or support areas"
                    ),
                ),
                ("program_of_interest", models.CharField(blank=True, max_length=200)),
                ("parent_name", models.CharField(max_length=120)),
                ("parent_email", models.EmailField(max_length=254)),
                (
                    "parent_phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid phone number.",
                                regex="^[\\d\\s\\+\\-\\(\\)]{7,20}$",
                            )
                        ],
                    ),
                ),
                (
                    "preferred_contact",
                    models.CharField(
                        choices=[
                            ("phone", "Phone"),
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        default="whatsapp",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("consent_privacy", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("scheduled", "Visit Scheduled"),
                            ("enrolled", "Enrolled"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Internal staff notes"),
                ),
            ],
            options={
                "verbose_name": "Admission enquiry",
                "verbose_name_plural": "Admission enquiries",
                "ordering": ["-created_at"],
            },
        ),
    ]
